/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Hasanaa e-commerce API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Admin login
 */
export const AdminLoginBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export const AdminLoginResponse = zod.object({
  success: zod.boolean(),
  admin: zod.string(),
});

/**
 * @summary Admin logout
 */
export const AdminLogoutResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get current admin session
 */
export const GetAdminMeResponse = zod.object({
  authenticated: zod.boolean(),
  admin: zod.string().nullable(),
});

/**
 * @summary List all banners
 */
export const ListBannersResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  subtitle: zod.string().nullable(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullable(),
  categoryId: zod.number().nullable(),
  subcategoryId: zod.number().nullable(),
  position: zod.string(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListBannersResponse = zod.array(ListBannersResponseItem);

/**
 * @summary Create a banner
 */
export const CreateBannerBody = zod.object({
  title: zod.string(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullish(),
  categoryId: zod.number().nullish(),
  subcategoryId: zod.number().nullish(),
  position: zod.string().optional(),
  isActive: zod.boolean().optional(),
  sortOrder: zod.number().optional(),
});

/**
 * @summary Get a banner
 */
export const GetBannerParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBannerResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  subtitle: zod.string().nullable(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullable(),
  categoryId: zod.number().nullable(),
  subcategoryId: zod.number().nullable(),
  position: zod.string(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update a banner
 */
export const UpdateBannerParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBannerBody = zod.object({
  title: zod.string().nullish(),
  subtitle: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  linkUrl: zod.string().nullish(),
  categoryId: zod.number().nullish(),
  subcategoryId: zod.number().nullish(),
  position: zod.string().nullish(),
  isActive: zod.boolean().nullish(),
  sortOrder: zod.number().nullish(),
});

export const UpdateBannerResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  subtitle: zod.string().nullable(),
  imageUrl: zod.string(),
  linkUrl: zod.string().nullable(),
  categoryId: zod.number().nullable(),
  subcategoryId: zod.number().nullable(),
  position: zod.string(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a banner
 */
export const DeleteBannerParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  imageUrl: zod.string().nullable(),
  parentTag: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem);

/**
 * @summary Create a category
 */
export const CreateCategoryBody = zod.object({
  name: zod.string(),
  slug: zod.string(),
  imageUrl: zod.string().nullish(),
  parentTag: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  sortOrder: zod.number().optional(),
});

/**
 * @summary Get a category with its products and subcategories
 */
export const GetCategoryParams = zod.object({
  id: zod.coerce.number(),
});

export const GetCategoryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  imageUrl: zod.string().nullable(),
  parentTag: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  subcategories: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      slug: zod.string(),
      categoryId: zod.number(),
      imageUrl: zod.string().nullable(),
      isActive: zod.boolean(),
      sortOrder: zod.number(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
    }),
  ),
  products: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      description: zod.string().nullable(),
      price: zod.string(),
      originalPrice: zod.string().nullable(),
      imageUrl: zod.string().nullable(),
      images: zod.array(zod.string()),
      sizeChartUrl: zod.string().nullable(),
      variantIds: zod.array(zod.number()),
      variants: zod.array(
        zod.object({
          id: zod.number(),
          name: zod.string(),
          imageUrl: zod.string().nullable(),
          price: zod.string(),
          colors: zod.array(zod.string()),
        }),
      ),
      categoryId: zod.number().nullable(),
      categoryName: zod.string().nullable(),
      subcategoryId: zod.number().nullable(),
      subcategoryName: zod.string().nullable(),
      inStock: zod.boolean(),
      isFeatured: zod.boolean(),
      sizes: zod.array(zod.string()),
      colors: zod.array(zod.string()),
      createdAt: zod.string(),
      updatedAt: zod.string(),
    }),
  ),
});

/**
 * @summary Update a category
 */
export const UpdateCategoryParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateCategoryBody = zod.object({
  name: zod.string().nullish(),
  slug: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  parentTag: zod.string().nullish(),
  isActive: zod.boolean().nullish(),
  sortOrder: zod.number().nullish(),
});

export const UpdateCategoryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  imageUrl: zod.string().nullable(),
  parentTag: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a category
 */
export const DeleteCategoryParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List subcategories, optionally filtered by categoryId
 */
export const ListSubcategoriesQueryParams = zod.object({
  categoryId: zod.coerce.number().nullish(),
});

export const ListSubcategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  imageUrl: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListSubcategoriesResponse = zod.array(
  ListSubcategoriesResponseItem,
);

/**
 * @summary Create a subcategory
 */
export const CreateSubcategoryBody = zod.object({
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  sortOrder: zod.number().optional(),
});

/**
 * @summary Get a subcategory with its products
 */
export const GetSubcategoryParams = zod.object({
  id: zod.coerce.number(),
});

export const GetSubcategoryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  imageUrl: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  products: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      description: zod.string().nullable(),
      price: zod.string(),
      originalPrice: zod.string().nullable(),
      imageUrl: zod.string().nullable(),
      images: zod.array(zod.string()),
      sizeChartUrl: zod.string().nullable(),
      variantIds: zod.array(zod.number()),
      variants: zod.array(
        zod.object({
          id: zod.number(),
          name: zod.string(),
          imageUrl: zod.string().nullable(),
          price: zod.string(),
          colors: zod.array(zod.string()),
        }),
      ),
      categoryId: zod.number().nullable(),
      categoryName: zod.string().nullable(),
      subcategoryId: zod.number().nullable(),
      subcategoryName: zod.string().nullable(),
      inStock: zod.boolean(),
      isFeatured: zod.boolean(),
      sizes: zod.array(zod.string()),
      colors: zod.array(zod.string()),
      createdAt: zod.string(),
      updatedAt: zod.string(),
    }),
  ),
});

/**
 * @summary Update a subcategory
 */
export const UpdateSubcategoryParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateSubcategoryBody = zod.object({
  name: zod.string().nullish(),
  slug: zod.string().nullish(),
  categoryId: zod.number().nullish(),
  imageUrl: zod.string().nullish(),
  isActive: zod.boolean().nullish(),
  sortOrder: zod.number().nullish(),
});

export const UpdateSubcategoryResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  imageUrl: zod.string().nullable(),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a subcategory
 */
export const DeleteSubcategoryParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all products
 */
export const ListProductsQueryParams = zod.object({
  categoryId: zod.coerce.number().nullish(),
  subcategoryId: zod.coerce.number().nullish(),
  featured: zod.coerce.string().nullish(),
});

export const ListProductsResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullable(),
  price: zod.string(),
  originalPrice: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  images: zod.array(zod.string()),
  sizeChartUrl: zod.string().nullable(),
  variantIds: zod.array(zod.number()),
  variants: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      imageUrl: zod.string().nullable(),
      price: zod.string(),
      colors: zod.array(zod.string()),
    }),
  ),
  categoryId: zod.number().nullable(),
  categoryName: zod.string().nullable(),
  subcategoryId: zod.number().nullable(),
  subcategoryName: zod.string().nullable(),
  inStock: zod.boolean(),
  isFeatured: zod.boolean(),
  sizes: zod.array(zod.string()),
  colors: zod.array(zod.string()),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListProductsResponse = zod.array(ListProductsResponseItem);

/**
 * @summary Create a product
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.string(),
  originalPrice: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  images: zod.array(zod.string()).optional(),
  sizeChartUrl: zod.string().nullish(),
  variantIds: zod.array(zod.number()).optional(),
  categoryId: zod.number().nullish(),
  subcategoryId: zod.number().nullish(),
  inStock: zod.boolean().optional(),
  isFeatured: zod.boolean().optional(),
  sizes: zod.array(zod.string()).optional(),
  colors: zod.array(zod.string()).optional(),
});

/**
 * @summary Get a product
 */
export const GetProductParams = zod.object({
  id: zod.coerce.number(),
});

export const GetProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullable(),
  price: zod.string(),
  originalPrice: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  images: zod.array(zod.string()),
  sizeChartUrl: zod.string().nullable(),
  variantIds: zod.array(zod.number()),
  variants: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      imageUrl: zod.string().nullable(),
      price: zod.string(),
      colors: zod.array(zod.string()),
    }),
  ),
  categoryId: zod.number().nullable(),
  categoryName: zod.string().nullable(),
  subcategoryId: zod.number().nullable(),
  subcategoryName: zod.string().nullable(),
  inStock: zod.boolean(),
  isFeatured: zod.boolean(),
  sizes: zod.array(zod.string()),
  colors: zod.array(zod.string()),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string().nullish(),
  description: zod.string().nullish(),
  price: zod.string().nullish(),
  originalPrice: zod.string().nullish(),
  imageUrl: zod.string().nullish(),
  images: zod.array(zod.string()).optional(),
  sizeChartUrl: zod.string().nullish(),
  variantIds: zod.array(zod.number()).optional(),
  categoryId: zod.number().nullish(),
  subcategoryId: zod.number().nullish(),
  inStock: zod.boolean().nullish(),
  isFeatured: zod.boolean().nullish(),
  sizes: zod.array(zod.string()).optional(),
  colors: zod.array(zod.string()).optional(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  description: zod.string().nullable(),
  price: zod.string(),
  originalPrice: zod.string().nullable(),
  imageUrl: zod.string().nullable(),
  images: zod.array(zod.string()),
  sizeChartUrl: zod.string().nullable(),
  variantIds: zod.array(zod.number()),
  variants: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      imageUrl: zod.string().nullable(),
      price: zod.string(),
      colors: zod.array(zod.string()),
    }),
  ),
  categoryId: zod.number().nullable(),
  categoryName: zod.string().nullable(),
  subcategoryId: zod.number().nullable(),
  subcategoryName: zod.string().nullable(),
  inStock: zod.boolean(),
  isFeatured: zod.boolean(),
  sizes: zod.array(zod.string()),
  colors: zod.array(zod.string()),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List all orders (admin)
 */
export const ListOrdersResponseItem = zod.object({
  id: zod.number(),
  customerName: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string().nullable(),
  customerEmail: zod.string().nullable(),
  customerArea: zod.string().nullable(),
  deliveryCharge: zod.string(),
  vat: zod.string(),
  notes: zod.string().nullable(),
  status: zod.string(),
  totalAmount: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.string(),
      quantity: zod.number(),
      size: zod.string().nullable(),
      color: zod.string().nullable(),
      imageUrl: zod.string().nullable(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListOrdersResponse = zod.array(ListOrdersResponseItem);

/**
 * @summary Place a customer order
 */
export const CreateOrderBody = zod.object({
  customerName: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string().nullish(),
  customerEmail: zod.string().nullish(),
  customerArea: zod.string().nullish(),
  notes: zod.string().nullish(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      quantity: zod.number(),
      size: zod.string().nullish(),
      color: zod.string().nullish(),
    }),
  ),
});

/**
 * @summary Get an order
 */
export const GetOrderParams = zod.object({
  id: zod.coerce.number(),
});

export const GetOrderResponse = zod.object({
  id: zod.number(),
  customerName: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string().nullable(),
  customerEmail: zod.string().nullable(),
  customerArea: zod.string().nullable(),
  deliveryCharge: zod.string(),
  vat: zod.string(),
  notes: zod.string().nullable(),
  status: zod.string(),
  totalAmount: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.string(),
      quantity: zod.number(),
      size: zod.string().nullable(),
      color: zod.string().nullable(),
      imageUrl: zod.string().nullable(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update order status (admin)
 */
export const UpdateOrderStatusParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateOrderStatusBody = zod.object({
  status: zod.string(),
});

export const UpdateOrderStatusResponse = zod.object({
  id: zod.number(),
  customerName: zod.string(),
  customerPhone: zod.string(),
  customerAddress: zod.string(),
  customerCity: zod.string().nullable(),
  customerEmail: zod.string().nullable(),
  customerArea: zod.string().nullable(),
  deliveryCharge: zod.string(),
  vat: zod.string(),
  notes: zod.string().nullable(),
  status: zod.string(),
  totalAmount: zod.string(),
  items: zod.array(
    zod.object({
      productId: zod.number(),
      productName: zod.string(),
      price: zod.string(),
      quantity: zod.number(),
      size: zod.string().nullable(),
      color: zod.string().nullable(),
      imageUrl: zod.string().nullable(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Get order statistics (admin dashboard)
 */
export const GetOrderStatsResponse = zod.object({
  totalOrders: zod.number(),
  pendingOrders: zod.number(),
  confirmedOrders: zod.number(),
  deliveredOrders: zod.number(),
  cancelledOrders: zod.number(),
  totalRevenue: zod.string(),
  recentOrders: zod.array(
    zod.object({
      id: zod.number(),
      customerName: zod.string(),
      customerPhone: zod.string(),
      customerAddress: zod.string(),
      customerCity: zod.string().nullable(),
      customerEmail: zod.string().nullable(),
      customerArea: zod.string().nullable(),
      deliveryCharge: zod.string(),
      vat: zod.string(),
      notes: zod.string().nullable(),
      status: zod.string(),
      totalAmount: zod.string(),
      items: zod.array(
        zod.object({
          productId: zod.number(),
          productName: zod.string(),
          price: zod.string(),
          quantity: zod.number(),
          size: zod.string().nullable(),
          color: zod.string().nullable(),
          imageUrl: zod.string().nullable(),
        }),
      ),
      createdAt: zod.string(),
      updatedAt: zod.string(),
    }),
  ),
});

/**
 * @summary List all promotion blocks
 */
export const ListPromotionsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  gridType: zod.number().describe("2 for 2-column grid, 4 for 4-column grid"),
  position: zod.string().describe("top or bottom"),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  items: zod.array(
    zod.object({
      imageUrl: zod.string(),
      label: zod.string(),
      categoryId: zod.number().nullish(),
      subcategoryId: zod.number().nullish(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});
export const ListPromotionsResponse = zod.array(ListPromotionsResponseItem);

/**
 * @summary Create a promotion block
 */
export const CreatePromotionBody = zod.object({
  title: zod.string(),
  gridType: zod.number(),
  position: zod.string(),
  isActive: zod.boolean().optional(),
  sortOrder: zod.number().optional(),
  items: zod
    .array(
      zod.object({
        imageUrl: zod.string(),
        label: zod.string(),
        categoryId: zod.number().nullish(),
        subcategoryId: zod.number().nullish(),
      }),
    )
    .optional(),
});

/**
 * @summary Get a promotion block
 */
export const GetPromotionParams = zod.object({
  id: zod.coerce.number(),
});

export const GetPromotionResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  gridType: zod.number().describe("2 for 2-column grid, 4 for 4-column grid"),
  position: zod.string().describe("top or bottom"),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  items: zod.array(
    zod.object({
      imageUrl: zod.string(),
      label: zod.string(),
      categoryId: zod.number().nullish(),
      subcategoryId: zod.number().nullish(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update a promotion block
 */
export const UpdatePromotionParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdatePromotionBody = zod.object({
  title: zod.string().nullish(),
  gridType: zod.number().nullish(),
  position: zod.string().nullish(),
  isActive: zod.boolean().nullish(),
  sortOrder: zod.number().nullish(),
  items: zod
    .array(
      zod.object({
        imageUrl: zod.string(),
        label: zod.string(),
        categoryId: zod.number().nullish(),
        subcategoryId: zod.number().nullish(),
      }),
    )
    .optional(),
});

export const UpdatePromotionResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  gridType: zod.number().describe("2 for 2-column grid, 4 for 4-column grid"),
  position: zod.string().describe("top or bottom"),
  isActive: zod.boolean(),
  sortOrder: zod.number(),
  items: zod.array(
    zod.object({
      imageUrl: zod.string(),
      label: zod.string(),
      categoryId: zod.number().nullish(),
      subcategoryId: zod.number().nullish(),
    }),
  ),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a promotion block
 */
export const DeletePromotionParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Upload an image (base64)
 */
export const UploadImageBody = zod.object({
  data: zod.string().describe("Base64 encoded image data with data URI prefix"),
  filename: zod.string(),
});

export const UploadImageResponse = zod.object({
  url: zod.string(),
});

/**
 * @summary Get the current delivery charge
 */
export const GetDeliveryChargeResponse = zod.object({
  deliveryCharge: zod.number(),
  vat: zod.number(),
});

/**
 * @summary Update the current delivery charge (admin)
 */
export const UpdateDeliveryChargeBody = zod.object({
  deliveryCharge: zod.number(),
  vat: zod.number(),
});

export const UpdateDeliveryChargeResponse = zod.object({
  success: zod.boolean(),
  deliveryCharge: zod.number(),
  vat: zod.number(),
});
